### PR TITLE
java 6 -> java 7

### PR DESCRIPTION
**Pull request by granders**
@ewencp minimal change - addresses issue #34 

searched for java 6 references with 
`egrep -r "(jdk\s*6)|(java\s*6)" .`

### CODE REVIEW

**Comment by ewencp** [comment]
@granders That grep command won't find everything. For example:

* there's some checks in build.sh
* reference to the openjdk-6-jdk package in aws-init.sh
* muckrake/services/templates/cdh/yarn-env.sh hardcodes java6 path
* muckrake/services/hadoop.py looks like it hard codes some java6 paths

I think that's all of them, but using `git grep` for `java` and `jdk` should make sure we catch everything. This is just going to be a painful patch not because it's big, but because it really needs everything to be tested from scratch to make sure we caught everything.

**Comment by ijuma** [comment]
Is there something we can do to centralise JDK references so that it's easier to update in the future? Also, it may be nice to be able to test with more than one version. Even though Java 7 is the minimum version required, Java 8 is likely to be a better for projects that have the option (due to the various performance and observability improvements).

**Comment by ewencp** [comment]
The check in build.sh is just a minimum version check, so I'm not concerned about that one. It should change very rarely.

The reference in aws-init.sh is kind of outside the scope of the tests since this is just for the configuration of the test runner node in AWS. Maybe just make this configurable by having that script take a `--jdk <version>` flag?

The references in the Vagrantfile and vagrant provisioning scripts are similar in that they aren't part of ducktape tests, just config setup. Again, we could make them configurable by putting a config in the Vagrantfile and then passing it through to `base.sh`. We do something similar in the Kafka Vagrantfile to pass config options for ZK and broker nodes.

In the tests, we could at least centralize the reference for now in whichever class in hadoop.py ends up using them (or a base class). The reference in yarn-env.sh should be refactored to use a parameter passed into the template.

**Comment by ijuma** [comment]
Sounds good @ewencp . Perhaps worth filing an issue with your comment if we don't want to tackle that right now.

**Comment by granders** [comment]
- Added --jdk flag to aws-init.sh
- Centralized references to jdk in hadoop.py
- Opened #36 for Vagrant

Some of the muckrake tests almost certainly won't pass right now because a few have been broken by the recent changes to ducktape.

Given that, we have a couple options:
- Just merge it and iterate
- Wait to fix existing errors before merging

Thoughts?

**Comment by ewencp** [comment]
If some tests are broken anyway, as long as a from-scratch setup + some tests are working with this patch, lets work from there (ideally we could just verify that the same set of tests that were previously passing with ducktape's master branch are still passing). Then we can address remaining issues in a follow up.

As soon as we pin a ducktape release for Kafka, let's do the same in muckrake. We can be more agressive about releasing newer ducktape versions and using them in muckrake, but we should move get muckrake to a state where it's not depending on having specific un-tagged versions of ducktape in order to keep working.

**Comment by ewencp** [comment]
@granders All the tests seem to be passing for me with latest ducktape, I don't think there are any compatibility issues with recent ducktape changes. So this should be good to merge.

**Pull request merged**
