### PR TITLE
CC-20: Add tests for single table MySQL Kafka connector to validate type handling and incremental query modes.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@gwenshap @granders First tests for MySQL Kafka connector. Needs confluentinc/kafka-connect-jdbc#16 merged first.

**Comment by gwenshap** [comment]
I'm commenting on the test without reviewing the connector first, so maybe it makes no sense but...
* We are not testing for nulls in different columns? Especially the timestamp / id columns that we are using for offsets.

* We are not checking anything regarding which partitions the data ends up in? If we are using anything in the database (say, primary keys) to partition, it will be nice to validate

* More than one table and validating proper distribution between workers will be nice at some point too...

The tests that exist look good, so no reason not to merge this, but pointing out some things that will be useful.

**Comment by ewencp** [comment]
@gwenshap Yes, this is the first cut test. 

* For nulls, are you saying we should test what happens when we put null for the value? For timestamp, we'd expect it to be a `NOT NULL` column (which it is in MySQL by default since it's auto-filled). We might be able to validate this in the connector before generating any data, though I'm not sure we want to block someone from using it on a nullable column if they are *sure* it will never be null.
* Not sure we would want to do much more at this level than validate the keys. I'd expect correct partitioning would be validated elsewhere. That said, I suppose it also doesn't hurt to validate just by checking that all messages with the same key end up in the same partition. We'll have to figure out how to do that with the tools we currently have though -- I don't think console consumer outputs that info currently.
* I can extend one of these to use more than one table. When I add a distributed test that'll obviously also need multiple tables.

**Comment by gwenshap** [comment]
Nulls: Either validate that the column is not nullable or handle nulls very gracefully (and I'm not sure it is possible). We can't cryptically break and blame the users for not reading docs carefully enough. In either case, we need to test that.

For partitions: Yeah, I agree - getting source records to the right partition logic is not the business of the connector, so checking the key is enough.
So, we should probably test partitioning in the Kafka Connect system tests :)

**Comment by ewencp** [comment]
@gwenshap I submitted a PR for handling nullable columns for timestamp/increasing in the kafka-connect-jdbc repository. For partitions, is this even under the purview of Kafka Connect? I guess just because we want to validate the producer settings or something? I usually think of Kafka Connect as a user of the clients such that they shouldn't need to validate anything about their behavior, just the inputs and outputs they receive.

Other than that, anything to do with this patch?

**Pull request merged**
